### ISSUE TITLE
doesn't work anymore

### ISSUE THREAD

**Issue by isaka-james** [vincent-laizer/boomserver#1]
reconsider your api configuration, the code doesn't work

**Comment by vincent-laizer** [comment]
The backend api was hosted on heroku free service, sadly all free tier accounts were suspended. 
I'm looking for alternatives to freely host the python code.
Any suggestions are welcome

**Comment by isaka-james** [comment]
sorry @vincent-laizer  for late reply, consider using vercel.com, they have maintained to give free hosting for over a long time. that's a honest choice

**Comment by vincent-laizer** [comment]
It works now, I hosted it on a custom server. Test it and tell me about your experience

**Comment by isaka-james** [comment]
But you don't have **documentation/readme**? 
And due to my current situation i can't run on my local machine.
